"""erasdfcv

Revision ID: 15916f699cd3
Revises: 5f6d09e8804d
Create Date: 2025-07-30 13:44:38.453840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15916f699cd3'
down_revision = '5f6d09e8804d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
