"""Initial migration

Revision ID: 324198984331
Revises: eed10203284c
Create Date: 2025-07-28 15:41:45.383886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324198984331'
down_revision = 'eed10203284c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children_home_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('photos_home_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'children_homes', ['children_home_id'], ['id'])
        batch_op.drop_column('home_id')

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_column('childrens_home')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('childrens_home', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('photos_home_id_fkey'), 'children_homes', ['home_id'], ['id'])
        batch_op.drop_column('children_home_id')

    # ### end Alembic commands ###
