"""added phonr number column

Revision ID: 55bb124baa9f
Revises: 324198984331
Create Date: 2025-07-29 02:23:05.106822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bb124baa9f'
down_revision = '324198984331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_column('childrens_home')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('childrens_home', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
