"""qwadekjws

Revision ID: 5f6d09e8804d
Revises: b30da1038861
Create Date: 2025-07-29 12:51:04.007807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6d09e8804d'
down_revision = 'b30da1038861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('volunteers_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('volunteers_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
