"""creat etables

Revision ID: d93064dd54b7
Revises: b18e830569fc
Create Date: 2025-07-29 11:53:58.308641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93064dd54b7'
down_revision = 'b18e830569fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('volunteers_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('volunteers_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
