"""changed photo table to have home_id

Revision ID: eed10203284c
Revises: 819ad99b1ddf
Create Date: 2025-07-28 12:59:36.542226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed10203284c'
down_revision = '819ad99b1ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('photos_children_home_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'children_homes', ['home_id'], ['id'])
        batch_op.drop_column('children_home_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children_home_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('photos_children_home_id_fkey'), 'children_homes', ['children_home_id'], ['id'])
        batch_op.drop_column('home_id')

    # ### end Alembic commands ###
